Vagrant.configure("2") do |config|
  # Ubuntu image
  config.vm.box = "hashicorp-education/ubuntu-24-04"
  config.vm.box_version = "0.1.0"

  # Public network for real internet access
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443
  #config.vm.network "public_network", bridge: "enp5s0"

  # Run install script
  config.vm.provision "shell",
    name: "install-dependencies",
    path: "install-dependencies.sh"
end

